version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: relogio123
    volumes:
      - ./wp-content:/var/www/html/wp-content 
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: relogio123